-- Anomaly Detection Migration
-- Purpose: Add anomaly detection fields to transactions table
-- Date: 2026-01-03
--
-- This migration adds:
-- - Anomaly score (0-100)
-- - Anomaly flags (JSON array)
-- - Investigation status tracking
-- - ZKP anomaly proof field
-- - Threshold encrypted details (for court orders)
-- - Timestamps for flagging and clearing

-- [DOC] Wrap everything in a transaction so that if any ALTER fails,
-- [DOC] none of the changes are committed — the table stays in its
-- [DOC] original clean state and the migration can be re-run safely.
BEGIN;

-- [DOC] anomaly_score holds a number from 0 to 100 computed by the
-- [DOC] rule-based AML engine at transaction creation time.
-- [DOC] Score components: amount risk (0-40), velocity risk (0-30),
-- [DOC] structuring risk (0-30). A score >= 65 triggers a flag.
-- [DOC] Crucially, a high score does NOT block or freeze the transaction;
-- [DOC] the money moves normally and the flag is recorded alongside it.
-- Add anomaly_score column (0-100, default 0.00)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS anomaly_score NUMERIC(5, 2) DEFAULT 0.00 NOT NULL;

-- [DOC] anomaly_flags is a JSON array of string labels describing which
-- [DOC] specific AML rules fired, e.g. ["HIGH_VALUE", "VELOCITY"].
-- [DOC] Stored as JSON (not individual boolean columns) so that new rule
-- [DOC] types can be added without schema changes.
-- Add anomaly_flags column (JSON array of flag names)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS anomaly_flags JSON;

-- [DOC] requires_investigation is a simple boolean derived from
-- [DOC] anomaly_score >= 65. It is pre-computed and stored so that
-- [DOC] the regulator's dashboard can query flagged transactions with a
-- [DOC] single indexed column scan rather than a computed expression.
-- Add requires_investigation flag (score >= 65)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS requires_investigation BOOLEAN DEFAULT FALSE NOT NULL;

-- [DOC] zkp_anomaly_proof stores the Schnorr zero-knowledge proof that
-- [DOC] proves the anomaly score exceeds the threshold (>= 65) without
-- [DOC] revealing the actual score or the transaction amount.
-- [DOC] Format: JSON-serialised Schnorr sigma protocol (commitment,
-- [DOC] challenge, response) generated by core/crypto/anomaly_zkp.py.
-- [DOC] A verifier can check this proof without learning the amount.
-- [DOC] Stored as TEXT because the proof is a variable-length JSON blob;
-- [DOC] the old VARCHAR(66) field used for SHA-256 hashes is too small.
-- Add zkp_anomaly_proof column (zero-knowledge proof of anomaly)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS zkp_anomaly_proof TEXT;

-- [DOC] threshold_encrypted_details stores the full transaction details
-- [DOC] (sender IDX, receiver IDX, amount in paise, timestamp) encrypted
-- [DOC] with a unique per-transaction AES-256-GCM key. That key is then
-- [DOC] split via Nested Shamir secret sharing:
-- [DOC]   Outer 2-of-2: Company share + Court_Combined share
-- [DOC]   Inner 1-of-N: Court_Combined = any ONE of {FFA, FIU, FLEA, NTA}
-- [DOC] The column type was BYTEA in this original migration (raw binary).
-- [DOC] Migration 010 later changed it to TEXT (base64/hex encoded) for
-- [DOC] easier transport over JSON APIs. See migration 010 for context.
-- Add threshold_encrypted_details column (encrypted for court orders)
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS threshold_encrypted_details BYTEA;

-- [DOC] investigation_status tracks the lifecycle of a flagged transaction
-- [DOC] from first flag through regulator review to final disposition:
-- [DOC]   None               — not flagged (anomaly_score < 65)
-- [DOC]   PENDING            — flagged, awaiting assignment
-- [DOC]   UNDER_REVIEW       — regulator has opened a case
-- [DOC]   CLEARED            — manually cleared by regulator
-- [DOC]   AUTO_CLEARED       — cleared automatically (no activity in N days)
-- [DOC]   CONFIRMED_SUSPICIOUS — regulator confirmed wrongdoing; court order likely
-- Add investigation_status column
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS investigation_status VARCHAR(20);

-- [DOC] flagged_at records the exact moment the anomaly engine marked this
-- [DOC] transaction. Used to measure investigation response time and to
-- [DOC] implement the automatic-clearing policy (e.g., auto-clear after
-- [DOC] 90 days with no further activity).
-- Add flagged_at timestamp
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS flagged_at TIMESTAMP WITH TIME ZONE;

-- [DOC] cleared_at records when the investigation was closed, whether by
-- [DOC] a human regulator (CLEARED) or the automatic timer (AUTO_CLEARED).
-- [DOC] NULL if the transaction was never flagged or is still under review.
-- Add cleared_at timestamp
ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS cleared_at TIMESTAMP WITH TIME ZONE;

-- [DOC] Indexes below make the regulator dashboard fast. The most common
-- [DOC] queries are:
-- [DOC]   "Show all transactions with anomaly_score >= 65"  -> idx_tx_anomaly_score
-- [DOC]   "Show all transactions needing investigation"     -> idx_tx_requires_investigation
-- [DOC]   "Show all UNDER_REVIEW cases"                    -> idx_tx_investigation_status
-- [DOC]   "Show transactions flagged this week"             -> idx_tx_flagged_at
-- Create indexes for fast anomaly queries
CREATE INDEX IF NOT EXISTS idx_tx_anomaly_score
ON transactions(anomaly_score);

CREATE INDEX IF NOT EXISTS idx_tx_requires_investigation
ON transactions(requires_investigation);

CREATE INDEX IF NOT EXISTS idx_tx_investigation_status
ON transactions(investigation_status);

CREATE INDEX IF NOT EXISTS idx_tx_flagged_at
ON transactions(flagged_at);

-- Add comments to columns
COMMENT ON COLUMN transactions.anomaly_score IS 'Anomaly detection score (0-100, higher = more suspicious)';
COMMENT ON COLUMN transactions.anomaly_flags IS 'JSON array of anomaly flags detected';
COMMENT ON COLUMN transactions.requires_investigation IS 'Flagged for investigation if score >= 65';
COMMENT ON COLUMN transactions.zkp_anomaly_proof IS 'Zero-knowledge proof of anomaly flag (flag hidden)';
COMMENT ON COLUMN transactions.threshold_encrypted_details IS 'Threshold-encrypted transaction details (3-party: Company+Court+RBI)';
COMMENT ON COLUMN transactions.investigation_status IS 'Investigation status: None, PENDING, UNDER_REVIEW, CLEARED, AUTO_CLEARED, CONFIRMED_SUSPICIOUS';
COMMENT ON COLUMN transactions.flagged_at IS 'Timestamp when transaction was flagged';
COMMENT ON COLUMN transactions.cleared_at IS 'Timestamp when investigation cleared the transaction';

-- [DOC] COMMIT makes all of the above ALTER TABLE and CREATE INDEX
-- [DOC] statements permanent in the database. If any statement above
-- [DOC] raised an error, PostgreSQL will have already rolled back to the
-- [DOC] state at BEGIN and this COMMIT is a no-op.
COMMIT;

-- [DOC] Verification queries below are run after the migration to confirm
-- [DOC] that all eight new columns landed with the correct data types.
-- [DOC] The output is printed by the migration runner for the operator
-- [DOC] to review before continuing.
-- Verification queries
SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'transactions'
AND column_name IN (
    'anomaly_score',
    'anomaly_flags',
    'requires_investigation',
    'zkp_anomaly_proof',
    'threshold_encrypted_details',
    'investigation_status',
    'flagged_at',
    'cleared_at'
)
ORDER BY column_name;

-- [DOC] This second verification query lists all anomaly-related indexes
-- [DOC] that were created, confirming the naming convention was followed
-- [DOC] and the indexes are queryable.
-- Check indexes
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'transactions'
AND indexname LIKE 'idx_tx_%anomaly%' OR indexname LIKE 'idx_tx_%investigation%' OR indexname LIKE 'idx_tx_flagged%'
ORDER BY indexname;
