-- Migration 010: Real Cryptographic Field Expansion
-- Purpose: Expand commitment and nullifier columns from VARCHAR(66) to TEXT
--          to accommodate real Pedersen commitment outputs (130-char hex strings)
--          generated by core/crypto/real/pedersen.py.
--
--          Background: SHA-256 commitments are 32 bytes = 64 hex + "0x" = 66 chars.
--          Real Pedersen commitments are uncompressed EC points: 64 bytes = 128 hex
--          + "0x" prefix = 130 chars. The VARCHAR(66) field silently truncates these,
--          causing commitment verification failures.
--
-- Affects:  transactions.commitment     VARCHAR(66) -> TEXT
--           transactions.nullifier      VARCHAR(66) -> TEXT
--           consortium_banks.bbs_secret_key  (new column for BBS+ group signatures)
--
-- Safe to re-run: All statements use IF NOT EXISTS or TYPE change is idempotent.
-- Date: 2026-02-21

-- [DOC] ============================================================
-- [DOC] PART 1: Widen commitment / nullifier / commitment_salt columns
-- [DOC]
-- [DOC] Why did these need to change?
-- [DOC] The original schema used VARCHAR(66) because SHA-256 produces a
-- [DOC] 32-byte hash -> 64 hex characters + "0x" prefix = 66 characters.
-- [DOC] That was fine when commitments were just SHA-256 hashes.
-- [DOC]
-- [DOC] After migrating to real Pedersen commitments (secp256k1 elliptic
-- [DOC] curve), the commitment is an EC group point stored in SEC1
-- [DOC] uncompressed form: 04 || x (32 bytes) || y (32 bytes) = 65 bytes
-- [DOC] = 130 hex characters + "0x" prefix = 132 characters.
-- [DOC] Compressed form (02/03 || x) = 33 bytes = 66 hex + "0x" = 68 chars.
-- [DOC] Either way the old VARCHAR(66) silently truncated the value and
-- [DOC] commitment verification always failed. Widening to TEXT (unlimited
-- [DOC] length in PostgreSQL) future-proofs all three columns.
-- [DOC] ============================================================

-- ============================================================
-- PART 1: Expand commitment and nullifier to TEXT
-- ============================================================

-- [DOC] 1.1: Widen the commitment column.
-- [DOC] ALTER COLUMN ... TYPE TEXT is non-destructive for varchar->text
-- [DOC] in PostgreSQL: it is a metadata-only change (no row rewrite),
-- [DOC] completes instantly even on tables with millions of rows, and
-- [DOC] all existing values are preserved verbatim.
-- 1.1 Expand commitment field (was VARCHAR(66), now TEXT for 130-char Pedersen points)
ALTER TABLE transactions
    ALTER COLUMN commitment TYPE TEXT;

-- [DOC] 1.2: Widen the nullifier column.
-- [DOC] The nullifier is SHA-256(commitment || sender_idx || secret).
-- [DOC] Because the commitment itself is now a 130-char Pedersen point,
-- [DOC] the nullifier derivation input is longer, so the result is hashed
-- [DOC] again to 64 hex chars. However, keeping it as TEXT is consistent
-- [DOC] and allows the format to evolve without another migration.
-- [DOC] The UNIQUE constraint on nullifier is preserved automatically.
-- 1.2 Expand nullifier field (was VARCHAR(66) UNIQUE, now TEXT UNIQUE)
ALTER TABLE transactions
    ALTER COLUMN nullifier TYPE TEXT;

-- [DOC] 1.3: Widen commitment_salt (the random blinding factor r).
-- [DOC] r is the Pedersen blinding scalar: a random 256-bit integer
-- [DOC] stored as a 64-char hex string. VARCHAR(66) was borderline
-- [DOC] (64 hex + "0x" = 66 chars exactly), but TEXT removes any risk
-- [DOC] of truncation if the representation changes (e.g., base64).
-- 1.3 Expand commitment_salt field (was VARCHAR(66), now TEXT)
ALTER TABLE transactions
    ALTER COLUMN commitment_salt TYPE TEXT;

-- [DOC] ============================================================
-- [DOC] PART 2: Add BBS+ group signature key columns to consortium_banks
-- [DOC]
-- [DOC] BBS04 group signatures (Charm-Crypto, BN254 pairing group) give
-- [DOC] each consortium bank an anonymous signing key. When a bank votes
-- [DOC] to approve a transaction batch it signs its vote with this key.
-- [DOC] The signature proves a legitimate consortium member voted without
-- [DOC] revealing which one — full anonymity until an authorised opener
-- [DOC] (the regulatory authority) runs the group-open algorithm during
-- [DOC] a dispute to identify the specific bank.
-- [DOC]
-- [DOC] Each bank holds its own (bbs_secret_key, bbs_public_key) pair.
-- [DOC] Keys are generated once during setup_consortium_banks() in
-- [DOC] core/services/bank_account_service.py and stored here.
-- [DOC]
-- [DOC] Format: hex-encoded serialised group element from the BN254
-- [DOC] pairing group as produced by charm-crypto-framework 0.62.
-- [DOC] Length is variable (~200-400 chars) so TEXT is required.
-- [DOC] ============================================================

-- ============================================================
-- PART 2: Add BBS+ key column to consortium_banks
-- ============================================================

-- [DOC] 2.1: bbs_secret_key is held by each bank node locally.
-- [DOC] In production each bank node would load this from its HSM
-- [DOC] rather than from the database, but for the research prototype
-- [DOC] storing it here simplifies key distribution.
-- [DOC] IF NOT EXISTS makes this statement safe to re-run.
-- 2.1 BBS+ secret key for each bank (used by Charm-Crypto BBS+ group signature scheme)
--     Generated during bank setup; held securely by each bank node.
--     Format: hex-encoded serialised group element from BN254 pairing group.
ALTER TABLE consortium_banks
    ADD COLUMN IF NOT EXISTS bbs_secret_key TEXT,
    ADD COLUMN IF NOT EXISTS bbs_public_key TEXT;

-- [DOC] ============================================================
-- [DOC] PART 3: Validation queries
-- [DOC] These SELECT statements are run by run_migration_010.py after
-- [DOC] applying the changes. They confirm:
-- [DOC]   3.1 — all three transaction columns are now data_type = 'text'
-- [DOC]   3.2 — bbs_secret_key and bbs_public_key exist on consortium_banks
-- [DOC] The operator should review this output before starting the server.
-- [DOC] ============================================================

-- ============================================================
-- PART 3: Validation Queries
-- ============================================================

-- [DOC] 3.1: Query information_schema (PostgreSQL's built-in catalog of
-- [DOC] column metadata) to confirm the three widened columns now report
-- [DOC] data_type = 'text'. character_maximum_length will be NULL for
-- [DOC] TEXT columns (unlimited), confirming the change succeeded.
-- 3.1 Verify commitment column is now TEXT
SELECT
    column_name,
    data_type,
    character_maximum_length
FROM information_schema.columns
WHERE table_name = 'transactions'
  AND column_name IN ('commitment', 'nullifier', 'commitment_salt');

-- [DOC] 3.2: Confirm the two new BBS+ columns landed on consortium_banks.
-- [DOC] Both should show data_type = 'text'.
-- 3.2 Verify BBS+ columns on consortium_banks
SELECT
    column_name,
    data_type
FROM information_schema.columns
WHERE table_name = 'consortium_banks'
  AND column_name IN ('bbs_secret_key', 'bbs_public_key');

SELECT '✅ Migration 010 completed: commitment/nullifier/commitment_salt expanded to TEXT; BBS+ key columns added.' AS status;
